-- Human-in-the-loop review for recommendations generated by a trusted server-side worker.
-- Members never receive a recommendation before it is approved by authorized staff.

CREATE POLICY "tenant admins read recommendation review queue"
  ON public.ai_recommendations FOR SELECT TO authenticated
  USING (tenant_id = public.current_tenant_id() AND public.is_tenant_admin());

CREATE OR REPLACE FUNCTION public.set_ai_recommendation_reviewed_at()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  IF NEW.status IN ('approved', 'rejected') AND OLD.status IS DISTINCT FROM NEW.status THEN
    NEW.reviewed_at := COALESCE(NEW.reviewed_at, now());
  ELSIF NEW.status IN ('draft', 'pending_approval') THEN
    NEW.reviewed_at := NULL;
    NEW.reviewed_by := NULL;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER set_ai_recommendation_reviewed_at
  BEFORE UPDATE OF status ON public.ai_recommendations
  FOR EACH ROW EXECUTE FUNCTION public.set_ai_recommendation_reviewed_at();
